[project]
name = "rhodium-ds"
version = "0.1.0"
requires-python = ">=3.11"
# NOTE: Example of a package that is not in nix packages
dependencies = ["langchain>=0.1.0", "jupyterthemes>=0.20"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
