background = '#090E13'
border_fg = '#A4A7A4'
text_fg = '#C5C9C7'
dimmed_text_fg = '#A4A7A4'

# Input area
input_text_fg = '#c4746e'
result_count_fg = '#c4746e'

# Results list
result_name_fg = '#8ba4b0'
result_line_number_fg = '#c4b28a'
result_value_fg = '#a292a3'
selection_fg = '#C5C9C7'
selection_bg = '#393B44'
match_fg = '#E46876'

# Preview
preview_title_fg = '#E6C384'

# Mode indicators
channel_mode_fg = '#090E13'
channel_mode_bg = '#938AA9'
remote_control_mode_fg = '#090E13'
remote_control_mode_bg = '#87a987'
send_to_channel_mode_fg = '#7AA89F'
