[[cable_channel]]
name = "files"
source_command = "fd . --type f --type d --hidden --exclude .git --color=never | sort"
preview_command = '''
if [ -d "{}" ]; then
  eza -la --color=always --icons=always --group-directories-first "{}"
else
  bat -n --color=always --style=numbers,changes "{}" 2>/dev/null || file -b "{}"
fi
'''
