[metadata]
name = "git"
description = "Git operations and history"
requirements = ["git", "delta"]

[source]
command = '''git log --oneline --date=short --pretty="format:%h▐%s▐%an▐%cd" --color=never'''
display = "{split:▐:0} • {split:▐:1} [{split:▐:2}]"
output = "{split:▐:0}"

[preview]
command = "git show -p --stat --pretty=fuller --color=always {} | delta"

[keybindings]
shortcut = "f3"

[ui]
input_header = "Git History:"
