[[cable_channel]]
name = "git"
source_command = "git log --oneline --date=short --pretty=\"format:%h %s %an %cd\" --color=never"
preview_command = "git show -p --stat --pretty=fuller --color=always {0} | delta"
