[[cable_channel]]
name = "processes"
source_command = "ps aux | tail -n +2 | awk '{printf \"%s %s %s %s %s\\n\", $2, $1, $3, $4, $11}'"
preview_command = '''
echo "Process Details for PID: {0}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
ps -p {0} -o pid,ppid,user,comm,cmd,etime,pmem,pcpu 2>/dev/null || echo "Process not found"
'''
