[[cable_channel]]
name = "projects"
source_command = '''
fd -t d -d 3 '\.(git|go\.mod|Cargo\.toml|package\.json|pyproject\.toml|flake\.nix)$' \
  ~/dev 2>/dev/null | \
  xargs -I {} dirname {} | sort -u
'''
preview_command = '''
eza -la --color=always --icons=always --group-directories-first "{}" | head -20
echo
if [ -f "{}/README.md" ]; then
  echo "📖 README.md:"
  bat -n --color=always --style=plain "{}/README.md" 2>/dev/null | head -15
fi
'''
