[[cable_channel]]
name = "recent"
source_command = '''
fd -t f --changed-within 7d --exclude .git --color=never . | \
  xargs -I {} sh -c 'echo "$(stat -c %Y {} 2>/dev/null || stat -f %m {} 2>/dev/null) {}"' | \
  sort -rn | cut -d' ' -f2- | head -100
'''
preview_command = "bat -n --color=always --style=full {}"
