title: Rhodium
description: A hypermodular NixOS system built to stand the test of time
baseurl: "/rhodium"
url: "https://pabloagn.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - 01-about.md
  - 02-motivation.md
  - 03-tools.md
  - 04-features.md
  - 05-quick-start.md
  - 06-usage.md
  - 07-options.md
  - 08-keybinds.md
  - 09-showcase.md
  - 10-attributions.md

logo: /assets/logo.png
github_username: pabloagn
repository: rhodium
