title: Rhodium
description: A hypermodular NixOS system built to stand the test of time
baseurl: "/rhodium"
url: "https://pabloagn.github.io"

# Just the Docs theme
remote_theme: just-the-docs/just-the-docs

# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "Copyright &copy; 2025 Rhodium. Built with NixOS and distributed under the <a href=\"https://github.com/pabloagn/rhodium/blob/main/LICENSE\">MIT License</a>."

# Color scheme
color_scheme: light

# Logo
logo: "/assets/logo.png"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/pabloagn/rhodium"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/pabloagn/rhodium"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
